version: "3.7"

services:

  mongo-0:
    image: mongo:4.2.16
    restart: always
    healthcheck:
      test: "[ -f /data/health.check ] && exit 0 || exit 1"
      interval: 1s
      timeout: 30s
      retries: 300
    command: mongod --replSet rs0
    volumes:
      - ./mongodb:/app
      - ./mongodb/init:/docker-entrypoint-initdb.d:ro

  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo-0:27017/

  elastic-search:
    build:
      context: ./elastic-search
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
    healthcheck:
      test: "wget -q -O - http://localhost:9200/_cat/health"
      interval: 1s
      timeout: 30s
      retries: 300
    # volumes:
    #   - ./elasticsearch/elasticsearch.config.yml:/usr/share/elasticsearch/config/elasticsearch.yml

  monstache:
    image: rwynn/monstache:6.7.5
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./monstache:/app
    command: '-f /app/config.toml'
    depends_on:
      mongo:
        condition: service_started
      elastic-search:
        condition: service_healthy
    healthcheck:
      test: "wget -q -O - http://localhost:8080/healthz"
      interval: 1s
      timeout: 30s
      retries: 300
